"""Check committed INVENTED Swift golden against the published Python codec.

Run with python3 -B; imports only repository source/fixtures, never private input.
Expected constants are fixed in CorrespondenceGolden.swift, not regenerated by tests.
"""
import base64
import hashlib
from pathlib import Path
import re
import sys

root = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(root / "Tools/TripNomination"))
import correspondence_request as c
from test_correspondence_request import fixtures

p, x = fixtures()
key = "invented-é-e\u0301-東京-한글-\\-\n-\u2028-🚀-\x00"
for source in (p["source"], x["source"]):
    source["key"] = key
for rows in (p["evidence"], x["evidence"]):
    for row in rows:
        row["source"]["key"] = key
q = c.prepare(p, x)
a = c.approve(q, x, c.proposal_digest(q["payload"]), "invented-owner",
              "2001-01-01T00:00:00Z", c.CONFIRMATION)
raw = c.canonical(a)
expected = {
    "bytes": base64.b64encode(raw).decode(),
    "context": base64.b64encode(c.canonical(x)).decode(),
    "proposalSHA256": a["approval"]["proposalSHA256"],
    "approvedContentSHA256": a["approval"]["approvedContentSHA256"],
    "recordSHA256": hashlib.sha256(raw).hexdigest(),
}
actual = dict(re.findall(r'static let (\w+) = "([^"]*)"',
                        Path(__file__).with_name("CorrespondenceGolden.swift").read_text()))
if actual != expected:
    raise SystemExit("FAIL invented correspondence Python golden")
print("PASS invented correspondence Python golden (5 constants)")
